The intention of this notebook is to do exploratory data analysis (EDA) on the GPU metrics collected.

In [27]:
import pymongo 
from pymongo import MongoClient
import os 
from dotenv import load_dotenv, find_dotenv
import numpy as np
import pandas as pd

In [28]:
load_dotenv(find_dotenv())
my_password = os.environ.get("RAHUL_PASS")

documents = {}

In [29]:
try: 
    uri = f"mongodb+srv://rr1437:{my_password}@prometrics.h105zsq.mongodb.net/?retryWrites=true&w=majority&appName=ProMetrics"
    client = MongoClient(uri)

    database = client["main"]
    collection = database["init_stage"]

    results = collection.find({"Collect" : "True"})

    for index, result in enumerate(results):
        documents[index] = result
        # print(index, result)
        # print(result)

    client.close()

except Exception as e:
    raise Exception(
        "Recieved the following error:" + e
    )

In [30]:
documents = pd.DataFrame(documents)
documents = documents.T
documents.drop(columns=['_id'], inplace=True)

In [31]:
documents

,GPU Utilization (%),Power Draw (Watts),GPU Temp (°C),GPU Current Clock (MHz),Memory Current Clock (MHz),Memory Allocation Used (MB),Memory Utilization (%),GPU Stress,Current Time,Time Delta,Status,Iteration,Collect
0,0.0,24.17,23.0,135000000.0,877000000.0,5242880.0,0.0,Off,11:24:10,0,Live,1,True
1,0.0,24.17,23.0,135000000.0,877000000.0,5242880.0,0.0,Off,11:24:11,1,Live,2,True
2,0.0,24.17,23.0,135000000.0,877000000.0,5242880.0,0.0,Off,11:24:12,3,Live,3,True
3,0.0,24.17,23.0,135000000.0,877000000.0,5242880.0,0.0,Off,11:24:14,4,Live,4,True
4,0.0,24.17,23.0,135000000.0,877000000.0,5242880.0,0.0,Off,11:24:15,5,Live,5,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
212,0.0,25.34,32.0,135000000.0,877000000.0,5242880.0,0.0,Off,11:28:55,286,Live,213,True
213,0.0,25.34,32.0,135000000.0,877000000.0,5242880.0,0.0,Off,11:28:56,287,Live,214,True
214,0.0,25.34,32.0,135000000.0,877000000.0,5242880.0,0.0,Off,11:28:58,288,Live,215,True
215,0.0,25.34,32.0,135000000.0,877000000.0,5242880.0,0.0,Off,11:28:59,289,Live,216,True
216,0.0,25.34,32.0,135000000.0,877000000.0,5242880.0,0.0,Off,11:29:00,291,Live,217,True

In [32]:
clock_speeds = ['GPU Current Clock (MHz)', 'Memory Current Clock (MHz)', ]
clock_speeds_c = ['GPU Current Clock (GHz)', 'Memory Current Clock (GHz)', ]
for i in clock_speeds:
    documents[i] = documents[i]/1000
    documents.rename(columns={i: clock_speeds_c[clock_speeds.index(i)]}, inplace=True)

In [33]:
documents

,GPU Utilization (%),Power Draw (Watts),GPU Temp (°C),GPU Current Clock (GHz),Memory Current Clock (GHz),Memory Allocation Used (MB),Memory Utilization (%),GPU Stress,Current Time,Time Delta,Status,Iteration,Collect
0,0.0,24.17,23.0,135000.0,877000.0,5242880.0,0.0,Off,11:24:10,0,Live,1,True
1,0.0,24.17,23.0,135000.0,877000.0,5242880.0,0.0,Off,11:24:11,1,Live,2,True
2,0.0,24.17,23.0,135000.0,877000.0,5242880.0,0.0,Off,11:24:12,3,Live,3,True
3,0.0,24.17,23.0,135000.0,877000.0,5242880.0,0.0,Off,11:24:14,4,Live,4,True
4,0.0,24.17,23.0,135000.0,877000.0,5242880.0,0.0,Off,11:24:15,5,Live,5,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
212,0.0,25.34,32.0,135000.0,877000.0,5242880.0,0.0,Off,11:28:55,286,Live,213,True
213,0.0,25.34,32.0,135000.0,877000.0,5242880.0,0.0,Off,11:28:56,287,Live,214,True
214,0.0,25.34,32.0,135000.0,877000.0,5242880.0,0.0,Off,11:28:58,288,Live,215,True
215,0.0,25.34,32.0,135000.0,877000.0,5242880.0,0.0,Off,11:28:59,289,Live,216,True
216,0.0,25.34,32.0,135000.0,877000.0,5242880.0,0.0,Off,11:29:00,291,Live,217,True

In [35]:
documents.to_csv("../samples/hundred.csv")

In [36]:
top_results = pd.read_csv(r"../benchmarks/processes.csv")

In [37]:
top_results

        Iteration    PID  PPID                          CMD %MEM %CPU
0               0    685     2                   [nv_queue]  0.0  1.8
1               0  31806     2  [kworker/u96:0-mlx5_cmd_000  0.0  0.7
2               0  31808     2  [kworker/u96:1-mlx5_cmd_000  0.0  0.5
3               0   1565  1452         /usr/bin/gnome-shell  0.1  0.4
4               0  31704     2  [kworker/u96:3-mlx5_cmd_000  0.0  0.3
...           ...    ...   ...                          ...  ...  ...
198571        299  32525     2   [kworker/u96:1-mkey_cache]  0.0  0.0
198572        299  32526     2  [kworker/u96:2-mlx5_cmd_000  0.0  0.0
198573        299  32527     2  [kworker/u96:3-mlx5_cmd_000  0.0  0.0
198574        299  32528     2   [kworker/u96:6-mkey_cache]  0.0  0.0
198575        299  32607     2              [kworker/u98:0]  0.0  0.0

[198576 rows x 6 columns]