The intention of this notebook is to do exploratory data analysis (EDA) on the GPU metrics collected.

In [48]:
import pymongo 
from pymongo import MongoClient
import os 
from dotenv import load_dotenv, find_dotenv
import numpy as np
import pandas as pd

In [49]:
load_dotenv(find_dotenv())
my_password = os.environ.get("RAHUL_PASS")

documents = {}

In [50]:
try: 
    uri = f"mongodb+srv://rr1437:{my_password}@prometrics.h105zsq.mongodb.net/?retryWrites=true&w=majority&appName=ProMetrics"
    client = MongoClient(uri)

    database = client["main"]
    collection = database["init_stage"]

    results = collection.find({"Collect" : "True"})

    for index, result in enumerate(results):
        documents[index] = result
        # print(index, result)
        # print(result)

    client.close()

except Exception as e:
    raise Exception(
        "Recieved the following error:" + e
    )

In [51]:
documents = pd.DataFrame(documents)
documents = documents.T
documents.drop(columns=['_id'], inplace=True)

In [52]:
documents

,GPU Utilization (%),Power Draw (Watts),GPU Temp (°C),GPU Current Clock (MHz),Memory Current Clock (MHz),Memory Allocation Used (MB),Memory Utilization (%),GPU Stress,Current Time,Time Delta,Status,Iteration,Collect
0,0.0,24.07,23.0,135000000.0,877000000.0,5242880.0,0.0,Off,13:25:04,0,Live,1,True
1,0.0,24.07,23.0,135000000.0,877000000.0,5242880.0,0.0,Off,13:25:05,2,Live,2,True
2,0.0,24.07,23.0,135000000.0,877000000.0,5242880.0,0.0,Off,13:25:06,3,Live,3,True
3,0.0,24.07,23.0,135000000.0,877000000.0,5242880.0,0.0,Off,13:25:08,4,Live,4,True
4,0.0,24.07,23.0,135000000.0,877000000.0,5242880.0,0.0,Off,13:25:09,6,Live,5,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
205,0.0,26.5,39.0,135000000.0,877000000.0,5242880.0,0.0,Off,13:29:55,291,Live,206,True
206,0.0,25.34,33.0,135000000.0,877000000.0,5242880.0,0.0,Off,13:29:56,293,Live,207,True
207,0.0,25.34,33.0,135000000.0,877000000.0,5242880.0,0.0,Off,13:29:57,294,Live,208,True
208,0.0,25.34,33.0,135000000.0,877000000.0,5242880.0,0.0,Off,13:29:59,295,Live,209,True
209,0.0,25.34,33.0,135000000.0,877000000.0,5242880.0,0.0,Off,13:30:00,297,Live,210,True

In [53]:
clock_speeds = ['GPU Current Clock (MHz)', 'Memory Current Clock (MHz)', ]
clock_speeds_c = ['GPU Current Clock (GHz)', 'Memory Current Clock (GHz)', ]
for i in clock_speeds:
    documents[i] = documents[i]/1000
    documents.rename(columns={i: clock_speeds_c[clock_speeds.index(i)]}, inplace=True)

In [54]:
documents

,GPU Utilization (%),Power Draw (Watts),GPU Temp (°C),GPU Current Clock (GHz),Memory Current Clock (GHz),Memory Allocation Used (MB),Memory Utilization (%),GPU Stress,Current Time,Time Delta,Status,Iteration,Collect
0,0.0,24.07,23.0,135000.0,877000.0,5242880.0,0.0,Off,13:25:04,0,Live,1,True
1,0.0,24.07,23.0,135000.0,877000.0,5242880.0,0.0,Off,13:25:05,2,Live,2,True
2,0.0,24.07,23.0,135000.0,877000.0,5242880.0,0.0,Off,13:25:06,3,Live,3,True
3,0.0,24.07,23.0,135000.0,877000.0,5242880.0,0.0,Off,13:25:08,4,Live,4,True
4,0.0,24.07,23.0,135000.0,877000.0,5242880.0,0.0,Off,13:25:09,6,Live,5,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
205,0.0,26.5,39.0,135000.0,877000.0,5242880.0,0.0,Off,13:29:55,291,Live,206,True
206,0.0,25.34,33.0,135000.0,877000.0,5242880.0,0.0,Off,13:29:56,293,Live,207,True
207,0.0,25.34,33.0,135000.0,877000.0,5242880.0,0.0,Off,13:29:57,294,Live,208,True
208,0.0,25.34,33.0,135000.0,877000.0,5242880.0,0.0,Off,13:29:59,295,Live,209,True
209,0.0,25.34,33.0,135000.0,877000.0,5242880.0,0.0,Off,13:30:00,297,Live,210,True

In [55]:
documents.to_csv("../samples/hundred_true.csv")

In [56]:
top_results = pd.read_csv(r"../benchmarks/processes.csv")

In [57]:
top_results

        Iteration    PID  PPID                          CMD %MEM %CPU
0               0    685     2                   [nv_queue]  0.0  1.8
1               0  31806     2  [kworker/u96:0-mlx5_cmd_000  0.0  0.7
2               0  31808     2  [kworker/u96:1-mlx5_cmd_000  0.0  0.5
3               0   1565  1452         /usr/bin/gnome-shell  0.1  0.4
4               0  31704     2  [kworker/u96:3-mlx5_cmd_000  0.0  0.3
...           ...    ...   ...                          ...  ...  ...
198571        299  32525     2   [kworker/u96:1-mkey_cache]  0.0  0.0
198572        299  32526     2  [kworker/u96:2-mlx5_cmd_000  0.0  0.0
198573        299  32527     2  [kworker/u96:3-mlx5_cmd_000  0.0  0.0
198574        299  32528     2   [kworker/u96:6-mkey_cache]  0.0  0.0
198575        299  32607     2              [kworker/u98:0]  0.0  0.0

[198576 rows x 6 columns]